Repository perlin-network/noise, pull requests merged in 2018-08, with the labels that each got.

#139 network: code cleanup, get rid of glog.Fatal in Dial
  network/network.go
Labels: feature

#140 network: resolve race conditions in tests
  go.mod
  network/plugin_test.go
  test/end2end_test.go
Labels: bug

#141 Made package 'protobufs' an internal package.
  .gitignore
  internal/protobuf/stream.pb.go
  internal/protobuf/stream.proto
  internal/test/end2end_test.go
  internal/test/mailbox.go
  internal/test/protobuf/test.pb.go
  internal/test/protobuf/test.proto
  internal/test/protobuf/testpb_test.go
  network/backoff/plugin.go
  network/client.go
  network/discovery/plugin.go
  network/discovery/rpc.go
  network/network.go
  network/network_interface.go
  network/stream.go
  network/utils.go
  network/utils_test.go
  peer/identity.go
Labels: feature

#142 network: use recv window
  network/network.go
  network/recv_window.go
  network/recv_window_test.go
Labels: bug

#143 network: recv window range method
  network/recv_window.go
  network/recv_window_test.go
Labels: feature

#144 network: fix recv window behaviour
  network/recv_window.go
  network/recv_window_test.go
Labels: bug

#146 network: simplify network.Accept
  network/builder.go
  network/client.go
  network/network.go
Labels: feature

#149 network: do no expose private fields
  network/backoff/plugin.go
  network/builder.go
  network/client.go
  network/nat/plugin_test.go
  network/network.go
  network/plugin_test.go
Labels: feature

#148 Peer ID is public key hash
  dht/routes.go
  dht/routes_test.go
  examples/proxy/messages/proxy.pb.go
  examples/proxy/messages/proxy.proto
  examples/proxy/proxy_test.go
  examples/request_benchmark/messages/load.pb.go
  examples/request_benchmark/messages/loadpb_test.go
  go.mod
  internal/protobuf/stream.pb.go
  internal/protobuf/stream.proto
  internal/test/protobuf/test.pb.go
  internal/test/protobuf/testpb_test.go
  network/utils.go
  peer/identity.go
  peer/identity_test.go
Labels: feature

#150 network: add tests
  internal/test/end2end_test.go
  network/network_interface.go
  network/network_test.go
  network/network_utils_test.go
Labels: tests

#151 network: improve docs
  network/client.go
  network/network.go
  network/transport/kcp.go
  network/transport/tcp.go
  network/transport/transport.go
Labels: enhancement
