Repository perlin-network/noise, pull requests merged in 2018-07, with the labels that each got.

#100 Initial CI configuration.
  .travis.yml
  go.mod
Labels: feature

#102 Readme reports.
  README.md
Labels: feature

#103 network/builders: Removed package and moved it to network/builder.go.
  README.md
  examples/basic/example_test.go
  examples/chat/main.go
  examples/cluster_benchmark/main.go
  examples/getting_started/main.go
  examples/local_benchmark/receiver/main.go
  examples/local_benchmark/sender/main.go
  examples/proxy/proxy_test.go
  examples/stream/main.go
  examples/topologies/topologies.go
  network/address_test.go
  network/backoff/plugin_test.go
  network/builder.go
  network/builder_test.go
  network/nat/plugin.go
  network/network.go
  network/plugin_test.go
  network/ring_buffer.go
  network/ring_buffer_test.go
  network/stream.go
  network/utils.go
  network/utils_test.go
Labels: feature

#104 Lint and exponential backoff duration fixes.
  examples/basic/example_test.go
  examples/chat/main.go
  examples/getting_started/main.go
  examples/proxy/proxy_test.go
  network/backoff/backoff.go
  network/network.go
Labels: bug

#106 Additional NAT traversal techniques.
  README.md
  examples/getting_started/main.go
  go.mod
  network/nat/plugin.go
  network/nat/upnp.go
Labels: feature

#105 Recompile protobufs using gogofaster
  .gitignore
  README.md
  examples/basic/messages/basic.pb.go
  examples/basic/messages/basic.proto
  examples/basic/messages/basicpb_test.go
  examples/chat/messages/chat.pb.go
  examples/chat/messages/chat.proto
  examples/chat/messages/chatpb_test.go
  examples/cluster_benchmark/messages/bench.pb.go
  examples/cluster_benchmark/messages/bench.proto
  examples/cluster_benchmark/messages/benchpb_test.go
  examples/local_benchmark/messages/basic.pb.go
  examples/local_benchmark/messages/basic.proto
  examples/local_benchmark/messages/basicpb_test.go
  examples/proxy/messages/proxy.pb.go
  examples/proxy/messages/proxy.proto
  examples/proxy/messages/proxypb_test.go
  examples/topologies/messages/topology.pb.go
  examples/topologies/messages/topology.proto
  examples/topologies/messages/topologypb_test.go
  go.mod
  network/client.go
  network/message.go
  network/network.go
  network/rpc/request.go
  network/stream.go
  protobuf/stream.pb.go
  protobuf/stream.proto
  scripts.go
Labels: feature

#114 Generalize recv window.
  go.sum
  network/network.go
  network/recv_window.go
Labels: feature

#115 Add benchmarks for crypto providers.
  crypto/blake2b/blake2b_test.go
  crypto/ed25519/ed25519_test.go
  go.mod
  network/recv_window.go
Labels: feature

#121 network/builder: add BuilderOptions
  .codecov.yml
  network/address.go
  network/address_test.go
  network/builder.go
  network/builder_test.go
  network/nat/plugin.go
  network/network.go
  network/stream.go
Labels: feature

#118 Add end-to-end tests.
  .travis.yml
  crypto/ed25519/ed25519.go
  crypto/ed25519/ed25519_test.go
  crypto/keypair.go
  crypto/mocks/mock_signature_policy.go
  crypto/policy.go
  crypto/test/keypair_test.go
  network/address_test.go
  network/backoff/plugin_test.go
  network/builder.go
  network/builder_test.go
  network/network.go
  test/end2end_test.go
  test/mailbox.go
  test/protobuf/test.pb.go
  test/protobuf/test.proto
  test/protobuf/testpb_test.go
Labels: bug, feature

#124 Optimize BLAKE2B and Ed25519.
  crypto/blake2b/blake2b.go
  crypto/ed25519/base.go
  crypto/ed25519/base_test.go
  crypto/ed25519/ed25519.go
  crypto/ed25519/internal/edwards25519/const.go
  crypto/ed25519/internal/edwards25519/const_amd64.go
  crypto/ed25519/internal/edwards25519/const_amd64_gen.go
  crypto/ed25519/internal/edwards25519/fe.go
  crypto/ed25519/internal/edwards25519/fe_amd64.go
  crypto/ed25519/internal/edwards25519/fe_mul_amd64.s
  crypto/ed25519/internal/edwards25519/fe_square_amd64.s
  crypto/ed25519/internal/edwards25519/field.go
  crypto/ed25519/internal/edwards25519/group.go
  crypto/ed25519/internal/edwards25519/scalar.go
  crypto/ed25519/testdata/sign.input.gz
  go.mod
Labels: feature

#125 Fix coverpkg error on codecov.
  crypto/keypair_test.go
Labels: bug

#129 Dial local IP in spite of NAT Traversal.
  examples/local_benchmark/receiver/main.go
  examples/proxy/proxy_test.go
  network/builder.go
  network/builder_test.go
  network/client.go
  network/config.go
  network/nat/plugin.go
  network/nat/plugin_test.go
  network/network.go
  network/network_interface.go
  network/stream.go
Labels: bug

#131 Fix CI, clean up logs.
  .travis.yml
  README.md
  go.mod
  network/network.go
  network/stream.go
Labels: bug

#132 Fix request/response race condition.
  README.md
  examples/proxy/proxy_test.go
  network/client.go
  network/client_load_test/main.go
  network/client_load_test/main_test.go
  network/client_load_test/messages/load.pb.go
  network/client_load_test/messages/load.proto
  network/client_load_test/messages/loadpb_test.go
  network/network.go
  protobuf/stream.pb.go
  protobuf/stream.proto
Labels: bug
