Repository perlin-network/noise, pull requests merged in 2019-02, with the labels that each got.

#196 Implement 'blocks' concept into protocol API for Noise v2.
  callbacks.go
  callbacks/mod.go
  callbacks/opcode.go
  callbacks/reduce.go
  callbacks/reduce_test.go
  callbacks/sequential.go
  callbacks/sequential_test.go
  cipher/aead/mod.go
  examples/chat/main.go
  handshake/ecdh/mod.go
  handshake/ecdh/msg.go
  msg.go
  msg_test.go
  node.go
  peer.go
  protocol/cipher.go
  protocol/handshake.go
  protocol/identity.go
  protocol/mod.go
  protocol/network.go
  rpc/mod.go
  skademlia/broadcast.go
  skademlia/id.go
  skademlia/identity.go
  skademlia/mod.go
  skademlia/msg.go
  skademlia/rpc.go
  skademlia/table.go
  transport/bufconn/bufconn.go
  transport/buffered.go
  transport/tcp.go
  transport/transport_test.go
Labels: enhancement, feature

#202 Provide methods for global read locking/unlocking for peers, and have atomic ACKs for AEAD.
  cipher/aead/mod.go
  cipher/aead/msg.go
  examples/benchmark/main.go
  examples/chat/main.go
  handshake/ecdh/mod.go
  handshake/ecdh/msg.go
  peer.go
Labels: bug

#201 Implement tests in payload package.
  payload/reader_test.go
  payload/writer_test.go
Labels: tests

#203 S/Kademlia package tests.
  examples/chat/main.go
  examples/e2e/e2e.go
  examples/e2e/e2e_test.go
  identity/ed25519/mod.go
  identity/ed25519/mod_test.go
  node.go
  skademlia/id.go
  skademlia/id_test.go
  skademlia/mod.go
  skademlia/msg_test.go
  skademlia/rpc.go
  skademlia/table.go
  skademlia/table_test.go
Labels: enhancement, tests

#206 Tests and fixes for noise.Node, and `protocol` package.
  cipher/aead/mod_test.go
  examples/e2e/e2e_test.go
  node.go
  node_test.go
  params.go
  params_test.go
  peer.go
  protocol/identity_test.go
  protocol/mod.go
  protocol/mod_test.go
  transport/bufconn/bufconn.go
  transport/buffered.go
  transport/mod.go
  transport/tcp.go
  transport/transport_test.go
Labels: tests

#207 Tests for noise.Peer.
  peer_test.go
Labels: tests

#209 Fix race condition over the network for AEAD.
  callbacks/reduce.go
  cipher/aead/crypto.go
  cipher/aead/mod.go
  cipher/aead/mod_test.go
  examples/benchmark/main.go
  examples/chat/main.go
  examples/e2e/e2e_test.go
  node.go
  params.go
  peer.go
  protocol/mod.go
  skademlia/mod.go
  skademlia/rpc.go
  skademlia/table_test.go
  transport/tcp.go
Labels: bug

#210 Fix logic for gracefully stopping nodes/peers.
  cipher/aead/mod_test.go
  examples/e2e/e2e_test.go
  internal/bufconn/bufconn.go
  node.go
  peer.go
  peer_test.go
  protocol/mod.go
  transport/buffered.go
Labels: bug, enhancement

#212 Separate out signature schemes from identity keypairs.
  docs/src/identities.md
  docs/src/skademlia.md
  identity/ed25519/mod.go
  identity/ed25519/mod_test.go
  identity/keypair.go
  signature/eddsa/mod.go
  signature/eddsa/mod_test.go
  signature/scheme.go
  skademlia/keys.go
  skademlia/keys_test.go
  skademlia/mod.go
  skademlia/mod_test.go
Labels: enhancement
