Repository perlin-network/noise, pull requests merged in 2020-01, with the labels that each got.

#265 Align atomic values
  callbacks/sequential.go
Labels: bug

#269 Implement LRU eviction policy for connection pool, and reduce flakiness of Kademlia test.
  kademlia/protocol_test.go
  map.go
  node_options_test.go
Labels: enhancement, tests

#270 client, conn: remove idle timeout goroutine and use net.Conn read/write deadlines instead
  client.go
  conn.go
  node_test.go
Labels: enhancement
